use super::data::*;
use super::id::*;
use swash::{Stretch, Weight, Style, Attributes};

pub const STATIC_DATA: StaticCollectionData = StaticCollectionData {
    search_paths: &["c:/windows/fonts/"],
    families: &[
        StaticFamilyData { name: "Arial", lowercase_name: "arial", has_stretch: false, fonts: &[(FontId(0), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(3), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(1), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(2), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Arial Black", lowercase_name: "arial black", has_stretch: false, fonts: &[(FontId(4), Stretch::NORMAL, Weight(900), Style::Normal),]},
        StaticFamilyData { name: "Bahnschrift", lowercase_name: "bahnschrift", has_stretch: false, fonts: &[(FontId(5), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Calibri", lowercase_name: "calibri", has_stretch: false, fonts: &[(FontId(6), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(8), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(7), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(11), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Calibri Light", lowercase_name: "calibri light", has_stretch: false, fonts: &[(FontId(9), Stretch::NORMAL, Weight(300), Style::Normal),(FontId(10), Stretch::NORMAL, Weight(300), Style::Italic),]},
        StaticFamilyData { name: "Cambria", lowercase_name: "cambria", has_stretch: false, fonts: &[(FontId(12), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(15), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(14), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(16), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Cambria Math", lowercase_name: "cambria math", has_stretch: false, fonts: &[(FontId(13), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Candara", lowercase_name: "candara", has_stretch: false, fonts: &[(FontId(17), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(19), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(18), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(22), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Candara Light", lowercase_name: "candara light", has_stretch: false, fonts: &[(FontId(20), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(21), Stretch::NORMAL, Weight(400), Style::Italic),]},
        StaticFamilyData { name: "Comic Sans MS", lowercase_name: "comic sans ms", has_stretch: false, fonts: &[(FontId(23), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(25), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(24), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(26), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Consolas", lowercase_name: "consolas", has_stretch: false, fonts: &[(FontId(27), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(29), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(28), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(30), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Constantia", lowercase_name: "constantia", has_stretch: false, fonts: &[(FontId(31), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(33), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(32), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(34), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Corbel", lowercase_name: "corbel", has_stretch: false, fonts: &[(FontId(35), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(37), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(36), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(40), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Corbel Light", lowercase_name: "corbel light", has_stretch: false, fonts: &[(FontId(38), Stretch::NORMAL, Weight(300), Style::Normal),(FontId(39), Stretch::NORMAL, Weight(300), Style::Italic),]},
        StaticFamilyData { name: "Courier New", lowercase_name: "courier new", has_stretch: false, fonts: &[(FontId(41), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(44), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(42), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(43), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Ebrima", lowercase_name: "ebrima", has_stretch: false, fonts: &[(FontId(45), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(46), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Franklin Gothic Medium", lowercase_name: "franklin gothic medium", has_stretch: false, fonts: &[(FontId(47), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(48), Stretch::NORMAL, Weight(400), Style::Italic),]},
        StaticFamilyData { name: "Gabriola", lowercase_name: "gabriola", has_stretch: false, fonts: &[(FontId(49), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Gadugi", lowercase_name: "gadugi", has_stretch: false, fonts: &[(FontId(50), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(51), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Georgia", lowercase_name: "georgia", has_stretch: false, fonts: &[(FontId(52), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(54), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(53), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(55), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "HoloLens MDL2 Assets", lowercase_name: "hololens mdl2 assets", has_stretch: false, fonts: &[(FontId(57), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Impact", lowercase_name: "impact", has_stretch: true, fonts: &[(FontId(58), Stretch::CONDENSED, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Ink Free", lowercase_name: "ink free", has_stretch: false, fonts: &[(FontId(59), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Javanese Text", lowercase_name: "javanese text", has_stretch: false, fonts: &[(FontId(60), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Leelawadee UI", lowercase_name: "leelawadee ui", has_stretch: false, fonts: &[(FontId(63), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(62), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Leelawadee UI Semilight", lowercase_name: "leelawadee ui semilight", has_stretch: false, fonts: &[(FontId(64), Stretch::NORMAL, Weight(350), Style::Normal),]},
        StaticFamilyData { name: "Lucida Console", lowercase_name: "lucida console", has_stretch: true, fonts: &[(FontId(65), Stretch::SEMI_CONDENSED, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Lucida Sans Unicode", lowercase_name: "lucida sans unicode", has_stretch: false, fonts: &[(FontId(61), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Malgun Gothic", lowercase_name: "malgun gothic", has_stretch: false, fonts: &[(FontId(68), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(69), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Malgun Gothic Semilight", lowercase_name: "malgun gothic semilight", has_stretch: false, fonts: &[(FontId(70), Stretch::NORMAL, Weight(300), Style::Normal),]},
        StaticFamilyData { name: "Marlett", lowercase_name: "marlett", has_stretch: false, fonts: &[(FontId(71), Stretch::NORMAL, Weight(500), Style::Normal),]},
        StaticFamilyData { name: "Microsoft Himalaya", lowercase_name: "microsoft himalaya", has_stretch: false, fonts: &[(FontId(56), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Microsoft JhengHei", lowercase_name: "microsoft jhenghei", has_stretch: false, fonts: &[(FontId(82), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(66), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft JhengHei Light", lowercase_name: "microsoft jhenghei light", has_stretch: false, fonts: &[(FontId(84), Stretch::NORMAL, Weight(290), Style::Normal),]},
        StaticFamilyData { name: "Microsoft JhengHei UI", lowercase_name: "microsoft jhenghei ui", has_stretch: false, fonts: &[(FontId(83), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(67), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft JhengHei UI Light", lowercase_name: "microsoft jhenghei ui light", has_stretch: false, fonts: &[(FontId(85), Stretch::NORMAL, Weight(290), Style::Normal),]},
        StaticFamilyData { name: "Microsoft New Tai Lue", lowercase_name: "microsoft new tai lue", has_stretch: false, fonts: &[(FontId(97), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(98), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft PhagsPa", lowercase_name: "microsoft phagspa", has_stretch: false, fonts: &[(FontId(104), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(103), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft Sans Serif", lowercase_name: "microsoft sans serif", has_stretch: false, fonts: &[(FontId(72), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Microsoft Tai Le", lowercase_name: "microsoft tai le", has_stretch: false, fonts: &[(FontId(157), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(156), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft YaHei", lowercase_name: "microsoft yahei", has_stretch: false, fonts: &[(FontId(86), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(88), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft YaHei Light", lowercase_name: "microsoft yahei light", has_stretch: false, fonts: &[(FontId(90), Stretch::NORMAL, Weight(290), Style::Normal),]},
        StaticFamilyData { name: "Microsoft YaHei UI", lowercase_name: "microsoft yahei ui", has_stretch: false, fonts: &[(FontId(87), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(89), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Microsoft YaHei UI Light", lowercase_name: "microsoft yahei ui light", has_stretch: false, fonts: &[(FontId(91), Stretch::NORMAL, Weight(290), Style::Normal),]},
        StaticFamilyData { name: "Microsoft Yi Baiti", lowercase_name: "microsoft yi baiti", has_stretch: false, fonts: &[(FontId(92), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "MingLiU-ExtB", lowercase_name: "mingliu-extb", has_stretch: false, fonts: &[(FontId(73), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "MingLiU_HKSCS-ExtB", lowercase_name: "mingliu_hkscs-extb", has_stretch: false, fonts: &[(FontId(75), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Mongolian Baiti", lowercase_name: "mongolian baiti", has_stretch: false, fonts: &[(FontId(78), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "MS Gothic", lowercase_name: "ms gothic", has_stretch: false, fonts: &[(FontId(79), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "MS PGothic", lowercase_name: "ms pgothic", has_stretch: false, fonts: &[(FontId(81), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "MS UI Gothic", lowercase_name: "ms ui gothic", has_stretch: false, fonts: &[(FontId(80), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "MV Boli", lowercase_name: "mv boli", has_stretch: false, fonts: &[(FontId(93), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Myanmar Text", lowercase_name: "myanmar text", has_stretch: false, fonts: &[(FontId(76), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(77), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Nirmala UI", lowercase_name: "nirmala ui", has_stretch: false, fonts: &[(FontId(94), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(95), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Nirmala UI Semilight", lowercase_name: "nirmala ui semilight", has_stretch: false, fonts: &[(FontId(96), Stretch::NORMAL, Weight(350), Style::Normal),]},
        StaticFamilyData { name: "NSimSun", lowercase_name: "nsimsun", has_stretch: false, fonts: &[(FontId(126), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Palatino Linotype", lowercase_name: "palatino linotype", has_stretch: false, fonts: &[(FontId(99), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(102), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(100), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(101), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "PMingLiU-ExtB", lowercase_name: "pmingliu-extb", has_stretch: false, fonts: &[(FontId(74), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Segoe MDL2 Assets", lowercase_name: "segoe mdl2 assets", has_stretch: false, fonts: &[(FontId(105), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Segoe Print", lowercase_name: "segoe print", has_stretch: false, fonts: &[(FontId(106), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(107), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Segoe Script", lowercase_name: "segoe script", has_stretch: false, fonts: &[(FontId(108), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(109), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Segoe UI", lowercase_name: "segoe ui", has_stretch: false, fonts: &[(FontId(110), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(112), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(111), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(115), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Segoe UI Black", lowercase_name: "segoe ui black", has_stretch: false, fonts: &[(FontId(116), Stretch::NORMAL, Weight(900), Style::Normal),(FontId(117), Stretch::NORMAL, Weight(900), Style::Italic),]},
        StaticFamilyData { name: "Segoe UI Emoji", lowercase_name: "segoe ui emoji", has_stretch: false, fonts: &[(FontId(118), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Segoe UI Historic", lowercase_name: "segoe ui historic", has_stretch: false, fonts: &[(FontId(119), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Segoe UI Light", lowercase_name: "segoe ui light", has_stretch: false, fonts: &[(FontId(113), Stretch::NORMAL, Weight(300), Style::Normal),(FontId(120), Stretch::NORMAL, Weight(300), Style::Italic),]},
        StaticFamilyData { name: "Segoe UI Semibold", lowercase_name: "segoe ui semibold", has_stretch: false, fonts: &[(FontId(121), Stretch::NORMAL, Weight(600), Style::Normal),(FontId(122), Stretch::NORMAL, Weight(600), Style::Italic),]},
        StaticFamilyData { name: "Segoe UI Semilight", lowercase_name: "segoe ui semilight", has_stretch: false, fonts: &[(FontId(114), Stretch::NORMAL, Weight(350), Style::Normal),(FontId(123), Stretch::NORMAL, Weight(350), Style::Italic),]},
        StaticFamilyData { name: "Segoe UI Symbol", lowercase_name: "segoe ui symbol", has_stretch: false, fonts: &[(FontId(124), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "SimSun", lowercase_name: "simsun", has_stretch: false, fonts: &[(FontId(125), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "SimSun-ExtB", lowercase_name: "simsun-extb", has_stretch: false, fonts: &[(FontId(127), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Sitka Banner", lowercase_name: "sitka banner", has_stretch: false, fonts: &[(FontId(133), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(145), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(139), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(151), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Sitka Display", lowercase_name: "sitka display", has_stretch: false, fonts: &[(FontId(132), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(144), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(138), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(150), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Sitka Heading", lowercase_name: "sitka heading", has_stretch: false, fonts: &[(FontId(131), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(143), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(137), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(149), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Sitka Small", lowercase_name: "sitka small", has_stretch: false, fonts: &[(FontId(128), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(140), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(134), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(146), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Sitka Subheading", lowercase_name: "sitka subheading", has_stretch: false, fonts: &[(FontId(130), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(142), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(136), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(148), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Sitka Text", lowercase_name: "sitka text", has_stretch: false, fonts: &[(FontId(129), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(141), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(135), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(147), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Sylfaen", lowercase_name: "sylfaen", has_stretch: false, fonts: &[(FontId(152), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Symbol", lowercase_name: "symbol", has_stretch: false, fonts: &[(FontId(153), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Tahoma", lowercase_name: "tahoma", has_stretch: false, fonts: &[(FontId(154), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(155), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Times New Roman", lowercase_name: "times new roman", has_stretch: false, fonts: &[(FontId(158), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(161), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(159), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(160), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Trebuchet MS", lowercase_name: "trebuchet ms", has_stretch: false, fonts: &[(FontId(162), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(165), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(163), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(164), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Verdana", lowercase_name: "verdana", has_stretch: false, fonts: &[(FontId(166), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(168), Stretch::NORMAL, Weight(400), Style::Italic),(FontId(167), Stretch::NORMAL, Weight(700), Style::Normal),(FontId(169), Stretch::NORMAL, Weight(700), Style::Italic),]},
        StaticFamilyData { name: "Webdings", lowercase_name: "webdings", has_stretch: false, fonts: &[(FontId(170), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Wingdings", lowercase_name: "wingdings", has_stretch: false, fonts: &[(FontId(171), Stretch::NORMAL, Weight(400), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic", lowercase_name: "yu gothic", has_stretch: false, fonts: &[(FontId(177), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(172), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic Light", lowercase_name: "yu gothic light", has_stretch: false, fonts: &[(FontId(175), Stretch::NORMAL, Weight(300), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic Medium", lowercase_name: "yu gothic medium", has_stretch: false, fonts: &[(FontId(179), Stretch::NORMAL, Weight(500), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic UI", lowercase_name: "yu gothic ui", has_stretch: false, fonts: &[(FontId(180), Stretch::NORMAL, Weight(400), Style::Normal),(FontId(173), Stretch::NORMAL, Weight(700), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic UI Light", lowercase_name: "yu gothic ui light", has_stretch: false, fonts: &[(FontId(176), Stretch::NORMAL, Weight(300), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic UI Semibold", lowercase_name: "yu gothic ui semibold", has_stretch: false, fonts: &[(FontId(174), Stretch::NORMAL, Weight(600), Style::Normal),]},
        StaticFamilyData { name: "Yu Gothic UI Semilight", lowercase_name: "yu gothic ui semilight", has_stretch: false, fonts: &[(FontId(178), Stretch::NORMAL, Weight(350), Style::Normal),]},
    ],
    fonts: &[
        StaticFontData { family: FontFamilyId(0), attributes: Attributes(52633602), source: FontSourceId(0), index: 0 },
        StaticFontData { family: FontFamilyId(0), attributes: Attributes(52787202), source: FontSourceId(1), index: 0 },
        StaticFontData { family: FontFamilyId(0), attributes: Attributes(52787206), source: FontSourceId(2), index: 0 },
        StaticFontData { family: FontFamilyId(0), attributes: Attributes(52633606), source: FontSourceId(3), index: 0 },
        StaticFontData { family: FontFamilyId(1), attributes: Attributes(52889602), source: FontSourceId(4), index: 0 },
        StaticFontData { family: FontFamilyId(2), attributes: Attributes(857939970), source: FontSourceId(5), index: 0 },
        StaticFontData { family: FontFamilyId(3), attributes: Attributes(52633602), source: FontSourceId(6), index: 0 },
        StaticFontData { family: FontFamilyId(3), attributes: Attributes(52787202), source: FontSourceId(7), index: 0 },
        StaticFontData { family: FontFamilyId(3), attributes: Attributes(52633606), source: FontSourceId(8), index: 0 },
        StaticFontData { family: FontFamilyId(4), attributes: Attributes(52582402), source: FontSourceId(9), index: 0 },
        StaticFontData { family: FontFamilyId(4), attributes: Attributes(52582406), source: FontSourceId(10), index: 0 },
        StaticFontData { family: FontFamilyId(3), attributes: Attributes(52787206), source: FontSourceId(11), index: 0 },
        StaticFontData { family: FontFamilyId(5), attributes: Attributes(52633602), source: FontSourceId(12), index: 0 },
        StaticFontData { family: FontFamilyId(6), attributes: Attributes(52633602), source: FontSourceId(12), index: 1 },
        StaticFontData { family: FontFamilyId(5), attributes: Attributes(52787202), source: FontSourceId(13), index: 0 },
        StaticFontData { family: FontFamilyId(5), attributes: Attributes(52633606), source: FontSourceId(14), index: 0 },
        StaticFontData { family: FontFamilyId(5), attributes: Attributes(52787206), source: FontSourceId(15), index: 0 },
        StaticFontData { family: FontFamilyId(7), attributes: Attributes(52633602), source: FontSourceId(16), index: 0 },
        StaticFontData { family: FontFamilyId(7), attributes: Attributes(52787202), source: FontSourceId(17), index: 0 },
        StaticFontData { family: FontFamilyId(7), attributes: Attributes(52633606), source: FontSourceId(18), index: 0 },
        StaticFontData { family: FontFamilyId(8), attributes: Attributes(52633602), source: FontSourceId(19), index: 0 },
        StaticFontData { family: FontFamilyId(8), attributes: Attributes(52633606), source: FontSourceId(20), index: 0 },
        StaticFontData { family: FontFamilyId(7), attributes: Attributes(52787206), source: FontSourceId(21), index: 0 },
        StaticFontData { family: FontFamilyId(9), attributes: Attributes(52633602), source: FontSourceId(22), index: 0 },
        StaticFontData { family: FontFamilyId(9), attributes: Attributes(52787202), source: FontSourceId(23), index: 0 },
        StaticFontData { family: FontFamilyId(9), attributes: Attributes(52633606), source: FontSourceId(24), index: 0 },
        StaticFontData { family: FontFamilyId(9), attributes: Attributes(52787206), source: FontSourceId(25), index: 0 },
        StaticFontData { family: FontFamilyId(10), attributes: Attributes(52633602), source: FontSourceId(26), index: 0 },
        StaticFontData { family: FontFamilyId(10), attributes: Attributes(52787202), source: FontSourceId(27), index: 0 },
        StaticFontData { family: FontFamilyId(10), attributes: Attributes(52633606), source: FontSourceId(28), index: 0 },
        StaticFontData { family: FontFamilyId(10), attributes: Attributes(52787206), source: FontSourceId(29), index: 0 },
        StaticFontData { family: FontFamilyId(11), attributes: Attributes(52633602), source: FontSourceId(30), index: 0 },
        StaticFontData { family: FontFamilyId(11), attributes: Attributes(52787202), source: FontSourceId(31), index: 0 },
        StaticFontData { family: FontFamilyId(11), attributes: Attributes(52633606), source: FontSourceId(32), index: 0 },
        StaticFontData { family: FontFamilyId(11), attributes: Attributes(52787206), source: FontSourceId(33), index: 0 },
        StaticFontData { family: FontFamilyId(12), attributes: Attributes(52633602), source: FontSourceId(34), index: 0 },
        StaticFontData { family: FontFamilyId(12), attributes: Attributes(52787202), source: FontSourceId(35), index: 0 },
        StaticFontData { family: FontFamilyId(12), attributes: Attributes(52633606), source: FontSourceId(36), index: 0 },
        StaticFontData { family: FontFamilyId(13), attributes: Attributes(52582402), source: FontSourceId(37), index: 0 },
        StaticFontData { family: FontFamilyId(13), attributes: Attributes(52582406), source: FontSourceId(38), index: 0 },
        StaticFontData { family: FontFamilyId(12), attributes: Attributes(52787206), source: FontSourceId(39), index: 0 },
        StaticFontData { family: FontFamilyId(14), attributes: Attributes(52633602), source: FontSourceId(40), index: 0 },
        StaticFontData { family: FontFamilyId(14), attributes: Attributes(52787202), source: FontSourceId(41), index: 0 },
        StaticFontData { family: FontFamilyId(14), attributes: Attributes(52787206), source: FontSourceId(42), index: 0 },
        StaticFontData { family: FontFamilyId(14), attributes: Attributes(52633606), source: FontSourceId(43), index: 0 },
        StaticFontData { family: FontFamilyId(15), attributes: Attributes(52633602), source: FontSourceId(44), index: 0 },
        StaticFontData { family: FontFamilyId(15), attributes: Attributes(52787202), source: FontSourceId(45), index: 0 },
        StaticFontData { family: FontFamilyId(16), attributes: Attributes(52633602), source: FontSourceId(46), index: 0 },
        StaticFontData { family: FontFamilyId(16), attributes: Attributes(52633606), source: FontSourceId(47), index: 0 },
        StaticFontData { family: FontFamilyId(17), attributes: Attributes(52633602), source: FontSourceId(48), index: 0 },
        StaticFontData { family: FontFamilyId(18), attributes: Attributes(52633602), source: FontSourceId(49), index: 0 },
        StaticFontData { family: FontFamilyId(18), attributes: Attributes(52787202), source: FontSourceId(50), index: 0 },
        StaticFontData { family: FontFamilyId(19), attributes: Attributes(52633602), source: FontSourceId(51), index: 0 },
        StaticFontData { family: FontFamilyId(19), attributes: Attributes(52787202), source: FontSourceId(52), index: 0 },
        StaticFontData { family: FontFamilyId(19), attributes: Attributes(52633606), source: FontSourceId(53), index: 0 },
        StaticFontData { family: FontFamilyId(19), attributes: Attributes(52787206), source: FontSourceId(54), index: 0 },
        StaticFontData { family: FontFamilyId(31), attributes: Attributes(52633602), source: FontSourceId(55), index: 0 },
        StaticFontData { family: FontFamilyId(20), attributes: Attributes(52633602), source: FontSourceId(56), index: 0 },
        StaticFontData { family: FontFamilyId(21), attributes: Attributes(26419202), source: FontSourceId(57), index: 0 },
        StaticFontData { family: FontFamilyId(22), attributes: Attributes(52633602), source: FontSourceId(58), index: 0 },
        StaticFontData { family: FontFamilyId(23), attributes: Attributes(52633602), source: FontSourceId(59), index: 0 },
        StaticFontData { family: FontFamilyId(27), attributes: Attributes(52633602), source: FontSourceId(60), index: 0 },
        StaticFontData { family: FontFamilyId(24), attributes: Attributes(52787202), source: FontSourceId(61), index: 0 },
        StaticFontData { family: FontFamilyId(24), attributes: Attributes(52633602), source: FontSourceId(62), index: 0 },
        StaticFontData { family: FontFamilyId(25), attributes: Attributes(52608002), source: FontSourceId(63), index: 0 },
        StaticFontData { family: FontFamilyId(26), attributes: Attributes(39526402), source: FontSourceId(64), index: 0 },
        StaticFontData { family: FontFamilyId(32), attributes: Attributes(52787202), source: FontSourceId(65), index: 0 },
        StaticFontData { family: FontFamilyId(34), attributes: Attributes(52787202), source: FontSourceId(65), index: 1 },
        StaticFontData { family: FontFamilyId(28), attributes: Attributes(52633602), source: FontSourceId(66), index: 0 },
        StaticFontData { family: FontFamilyId(28), attributes: Attributes(52787202), source: FontSourceId(67), index: 0 },
        StaticFontData { family: FontFamilyId(29), attributes: Attributes(52582402), source: FontSourceId(68), index: 0 },
        StaticFontData { family: FontFamilyId(30), attributes: Attributes(52684802), source: FontSourceId(69), index: 0 },
        StaticFontData { family: FontFamilyId(38), attributes: Attributes(52633602), source: FontSourceId(70), index: 0 },
        StaticFontData { family: FontFamilyId(45), attributes: Attributes(52633602), source: FontSourceId(71), index: 0 },
        StaticFontData { family: FontFamilyId(57), attributes: Attributes(52633602), source: FontSourceId(71), index: 1 },
        StaticFontData { family: FontFamilyId(46), attributes: Attributes(52633602), source: FontSourceId(71), index: 2 },
        StaticFontData { family: FontFamilyId(52), attributes: Attributes(52633602), source: FontSourceId(72), index: 0 },
        StaticFontData { family: FontFamilyId(52), attributes: Attributes(52787202), source: FontSourceId(73), index: 0 },
        StaticFontData { family: FontFamilyId(47), attributes: Attributes(52633602), source: FontSourceId(74), index: 0 },
        StaticFontData { family: FontFamilyId(48), attributes: Attributes(52633602), source: FontSourceId(75), index: 0 },
        StaticFontData { family: FontFamilyId(50), attributes: Attributes(52633602), source: FontSourceId(75), index: 1 },
        StaticFontData { family: FontFamilyId(49), attributes: Attributes(52633602), source: FontSourceId(75), index: 2 },
        StaticFontData { family: FontFamilyId(32), attributes: Attributes(52633602), source: FontSourceId(76), index: 0 },
        StaticFontData { family: FontFamilyId(34), attributes: Attributes(52633602), source: FontSourceId(76), index: 1 },
        StaticFontData { family: FontFamilyId(33), attributes: Attributes(52577282), source: FontSourceId(77), index: 0 },
        StaticFontData { family: FontFamilyId(35), attributes: Attributes(52577282), source: FontSourceId(77), index: 1 },
        StaticFontData { family: FontFamilyId(40), attributes: Attributes(52633602), source: FontSourceId(78), index: 0 },
        StaticFontData { family: FontFamilyId(42), attributes: Attributes(52633602), source: FontSourceId(78), index: 1 },
        StaticFontData { family: FontFamilyId(40), attributes: Attributes(52787202), source: FontSourceId(79), index: 0 },
        StaticFontData { family: FontFamilyId(42), attributes: Attributes(52787202), source: FontSourceId(79), index: 1 },
        StaticFontData { family: FontFamilyId(41), attributes: Attributes(52577282), source: FontSourceId(80), index: 0 },
        StaticFontData { family: FontFamilyId(43), attributes: Attributes(52577282), source: FontSourceId(80), index: 1 },
        StaticFontData { family: FontFamilyId(44), attributes: Attributes(52633602), source: FontSourceId(81), index: 0 },
        StaticFontData { family: FontFamilyId(51), attributes: Attributes(52633602), source: FontSourceId(82), index: 0 },
        StaticFontData { family: FontFamilyId(53), attributes: Attributes(52633602), source: FontSourceId(83), index: 0 },
        StaticFontData { family: FontFamilyId(53), attributes: Attributes(52787202), source: FontSourceId(84), index: 0 },
        StaticFontData { family: FontFamilyId(54), attributes: Attributes(52608002), source: FontSourceId(85), index: 0 },
        StaticFontData { family: FontFamilyId(36), attributes: Attributes(52633602), source: FontSourceId(86), index: 0 },
        StaticFontData { family: FontFamilyId(36), attributes: Attributes(52787202), source: FontSourceId(87), index: 0 },
        StaticFontData { family: FontFamilyId(56), attributes: Attributes(52633602), source: FontSourceId(88), index: 0 },
        StaticFontData { family: FontFamilyId(56), attributes: Attributes(52787202), source: FontSourceId(89), index: 0 },
        StaticFontData { family: FontFamilyId(56), attributes: Attributes(52787206), source: FontSourceId(90), index: 0 },
        StaticFontData { family: FontFamilyId(56), attributes: Attributes(52633606), source: FontSourceId(91), index: 0 },
        StaticFontData { family: FontFamilyId(37), attributes: Attributes(52787202), source: FontSourceId(92), index: 0 },
        StaticFontData { family: FontFamilyId(37), attributes: Attributes(52633602), source: FontSourceId(93), index: 0 },
        StaticFontData { family: FontFamilyId(58), attributes: Attributes(52633602), source: FontSourceId(94), index: 0 },
        StaticFontData { family: FontFamilyId(59), attributes: Attributes(52633602), source: FontSourceId(95), index: 0 },
        StaticFontData { family: FontFamilyId(59), attributes: Attributes(52787202), source: FontSourceId(96), index: 0 },
        StaticFontData { family: FontFamilyId(60), attributes: Attributes(52633602), source: FontSourceId(97), index: 0 },
        StaticFontData { family: FontFamilyId(60), attributes: Attributes(52787202), source: FontSourceId(98), index: 0 },
        StaticFontData { family: FontFamilyId(61), attributes: Attributes(52633602), source: FontSourceId(99), index: 0 },
        StaticFontData { family: FontFamilyId(61), attributes: Attributes(52787202), source: FontSourceId(100), index: 0 },
        StaticFontData { family: FontFamilyId(61), attributes: Attributes(52633606), source: FontSourceId(101), index: 0 },
        StaticFontData { family: FontFamilyId(65), attributes: Attributes(52582402), source: FontSourceId(102), index: 0 },
        StaticFontData { family: FontFamilyId(67), attributes: Attributes(52608002), source: FontSourceId(103), index: 0 },
        StaticFontData { family: FontFamilyId(61), attributes: Attributes(52787206), source: FontSourceId(104), index: 0 },
        StaticFontData { family: FontFamilyId(62), attributes: Attributes(52889602), source: FontSourceId(105), index: 0 },
        StaticFontData { family: FontFamilyId(62), attributes: Attributes(52889606), source: FontSourceId(106), index: 0 },
        StaticFontData { family: FontFamilyId(63), attributes: Attributes(52633602), source: FontSourceId(107), index: 0 },
        StaticFontData { family: FontFamilyId(64), attributes: Attributes(52633602), source: FontSourceId(108), index: 0 },
        StaticFontData { family: FontFamilyId(65), attributes: Attributes(52582406), source: FontSourceId(109), index: 0 },
        StaticFontData { family: FontFamilyId(66), attributes: Attributes(52736002), source: FontSourceId(110), index: 0 },
        StaticFontData { family: FontFamilyId(66), attributes: Attributes(52736006), source: FontSourceId(111), index: 0 },
        StaticFontData { family: FontFamilyId(67), attributes: Attributes(52608006), source: FontSourceId(112), index: 0 },
        StaticFontData { family: FontFamilyId(68), attributes: Attributes(52633602), source: FontSourceId(113), index: 0 },
        StaticFontData { family: FontFamilyId(69), attributes: Attributes(52633602), source: FontSourceId(114), index: 0 },
        StaticFontData { family: FontFamilyId(55), attributes: Attributes(52633602), source: FontSourceId(114), index: 1 },
        StaticFontData { family: FontFamilyId(70), attributes: Attributes(52633602), source: FontSourceId(115), index: 0 },
        StaticFontData { family: FontFamilyId(74), attributes: Attributes(52633602), source: FontSourceId(116), index: 0 },
        StaticFontData { family: FontFamilyId(76), attributes: Attributes(52633602), source: FontSourceId(116), index: 1 },
        StaticFontData { family: FontFamilyId(75), attributes: Attributes(52633602), source: FontSourceId(116), index: 2 },
        StaticFontData { family: FontFamilyId(73), attributes: Attributes(52633602), source: FontSourceId(116), index: 3 },
        StaticFontData { family: FontFamilyId(72), attributes: Attributes(52633602), source: FontSourceId(116), index: 4 },
        StaticFontData { family: FontFamilyId(71), attributes: Attributes(52633602), source: FontSourceId(116), index: 5 },
        StaticFontData { family: FontFamilyId(74), attributes: Attributes(52787202), source: FontSourceId(117), index: 0 },
        StaticFontData { family: FontFamilyId(76), attributes: Attributes(52787202), source: FontSourceId(117), index: 1 },
        StaticFontData { family: FontFamilyId(75), attributes: Attributes(52787202), source: FontSourceId(117), index: 2 },
        StaticFontData { family: FontFamilyId(73), attributes: Attributes(52787202), source: FontSourceId(117), index: 3 },
        StaticFontData { family: FontFamilyId(72), attributes: Attributes(52787202), source: FontSourceId(117), index: 4 },
        StaticFontData { family: FontFamilyId(71), attributes: Attributes(52787202), source: FontSourceId(117), index: 5 },
        StaticFontData { family: FontFamilyId(74), attributes: Attributes(52633606), source: FontSourceId(118), index: 0 },
        StaticFontData { family: FontFamilyId(76), attributes: Attributes(52633606), source: FontSourceId(118), index: 1 },
        StaticFontData { family: FontFamilyId(75), attributes: Attributes(52633606), source: FontSourceId(118), index: 2 },
        StaticFontData { family: FontFamilyId(73), attributes: Attributes(52633606), source: FontSourceId(118), index: 3 },
        StaticFontData { family: FontFamilyId(72), attributes: Attributes(52633606), source: FontSourceId(118), index: 4 },
        StaticFontData { family: FontFamilyId(71), attributes: Attributes(52633606), source: FontSourceId(118), index: 5 },
        StaticFontData { family: FontFamilyId(74), attributes: Attributes(52787206), source: FontSourceId(119), index: 0 },
        StaticFontData { family: FontFamilyId(76), attributes: Attributes(52787206), source: FontSourceId(119), index: 1 },
        StaticFontData { family: FontFamilyId(75), attributes: Attributes(52787206), source: FontSourceId(119), index: 2 },
        StaticFontData { family: FontFamilyId(73), attributes: Attributes(52787206), source: FontSourceId(119), index: 3 },
        StaticFontData { family: FontFamilyId(72), attributes: Attributes(52787206), source: FontSourceId(119), index: 4 },
        StaticFontData { family: FontFamilyId(71), attributes: Attributes(52787206), source: FontSourceId(119), index: 5 },
        StaticFontData { family: FontFamilyId(77), attributes: Attributes(52633602), source: FontSourceId(120), index: 0 },
        StaticFontData { family: FontFamilyId(78), attributes: Attributes(52633602), source: FontSourceId(121), index: 0 },
        StaticFontData { family: FontFamilyId(79), attributes: Attributes(52633602), source: FontSourceId(122), index: 0 },
        StaticFontData { family: FontFamilyId(79), attributes: Attributes(52787202), source: FontSourceId(123), index: 0 },
        StaticFontData { family: FontFamilyId(39), attributes: Attributes(52787202), source: FontSourceId(124), index: 0 },
        StaticFontData { family: FontFamilyId(39), attributes: Attributes(52633602), source: FontSourceId(125), index: 0 },
        StaticFontData { family: FontFamilyId(80), attributes: Attributes(52633602), source: FontSourceId(126), index: 0 },
        StaticFontData { family: FontFamilyId(80), attributes: Attributes(52787202), source: FontSourceId(127), index: 0 },
        StaticFontData { family: FontFamilyId(80), attributes: Attributes(52787206), source: FontSourceId(128), index: 0 },
        StaticFontData { family: FontFamilyId(80), attributes: Attributes(52633606), source: FontSourceId(129), index: 0 },
        StaticFontData { family: FontFamilyId(81), attributes: Attributes(52633602), source: FontSourceId(130), index: 0 },
        StaticFontData { family: FontFamilyId(81), attributes: Attributes(52787202), source: FontSourceId(131), index: 0 },
        StaticFontData { family: FontFamilyId(81), attributes: Attributes(52787206), source: FontSourceId(132), index: 0 },
        StaticFontData { family: FontFamilyId(81), attributes: Attributes(52633606), source: FontSourceId(133), index: 0 },
        StaticFontData { family: FontFamilyId(82), attributes: Attributes(52633602), source: FontSourceId(134), index: 0 },
        StaticFontData { family: FontFamilyId(82), attributes: Attributes(52787202), source: FontSourceId(135), index: 0 },
        StaticFontData { family: FontFamilyId(82), attributes: Attributes(52633606), source: FontSourceId(136), index: 0 },
        StaticFontData { family: FontFamilyId(82), attributes: Attributes(52787206), source: FontSourceId(137), index: 0 },
        StaticFontData { family: FontFamilyId(83), attributes: Attributes(52633602), source: FontSourceId(138), index: 0 },
        StaticFontData { family: FontFamilyId(84), attributes: Attributes(52633602), source: FontSourceId(139), index: 0 },
        StaticFontData { family: FontFamilyId(85), attributes: Attributes(52787202), source: FontSourceId(140), index: 0 },
        StaticFontData { family: FontFamilyId(88), attributes: Attributes(52787202), source: FontSourceId(140), index: 1 },
        StaticFontData { family: FontFamilyId(90), attributes: Attributes(52736002), source: FontSourceId(140), index: 2 },
        StaticFontData { family: FontFamilyId(86), attributes: Attributes(52582402), source: FontSourceId(141), index: 0 },
        StaticFontData { family: FontFamilyId(89), attributes: Attributes(52582402), source: FontSourceId(141), index: 1 },
        StaticFontData { family: FontFamilyId(85), attributes: Attributes(52633602), source: FontSourceId(142), index: 0 },
        StaticFontData { family: FontFamilyId(91), attributes: Attributes(52608002), source: FontSourceId(142), index: 1 },
        StaticFontData { family: FontFamilyId(87), attributes: Attributes(52684802), source: FontSourceId(143), index: 0 },
        StaticFontData { family: FontFamilyId(88), attributes: Attributes(52633602), source: FontSourceId(143), index: 1 },
    ],
    sources: &[
        StaticSourceData { file_name: "arial.ttf" },
        StaticSourceData { file_name: "arialbd.ttf" },
        StaticSourceData { file_name: "arialbi.ttf" },
        StaticSourceData { file_name: "ariali.ttf" },
        StaticSourceData { file_name: "ariblk.ttf" },
        StaticSourceData { file_name: "bahnschrift.ttf" },
        StaticSourceData { file_name: "calibri.ttf" },
        StaticSourceData { file_name: "calibrib.ttf" },
        StaticSourceData { file_name: "calibrii.ttf" },
        StaticSourceData { file_name: "calibril.ttf" },
        StaticSourceData { file_name: "calibrili.ttf" },
        StaticSourceData { file_name: "calibriz.ttf" },
        StaticSourceData { file_name: "cambria.ttc" },
        StaticSourceData { file_name: "cambriab.ttf" },
        StaticSourceData { file_name: "cambriai.ttf" },
        StaticSourceData { file_name: "cambriaz.ttf" },
        StaticSourceData { file_name: "candara.ttf" },
        StaticSourceData { file_name: "candarab.ttf" },
        StaticSourceData { file_name: "candarai.ttf" },
        StaticSourceData { file_name: "candaral.ttf" },
        StaticSourceData { file_name: "candarali.ttf" },
        StaticSourceData { file_name: "candaraz.ttf" },
        StaticSourceData { file_name: "comic.ttf" },
        StaticSourceData { file_name: "comicbd.ttf" },
        StaticSourceData { file_name: "comici.ttf" },
        StaticSourceData { file_name: "comicz.ttf" },
        StaticSourceData { file_name: "consola.ttf" },
        StaticSourceData { file_name: "consolab.ttf" },
        StaticSourceData { file_name: "consolai.ttf" },
        StaticSourceData { file_name: "consolaz.ttf" },
        StaticSourceData { file_name: "constan.ttf" },
        StaticSourceData { file_name: "constanb.ttf" },
        StaticSourceData { file_name: "constani.ttf" },
        StaticSourceData { file_name: "constanz.ttf" },
        StaticSourceData { file_name: "corbel.ttf" },
        StaticSourceData { file_name: "corbelb.ttf" },
        StaticSourceData { file_name: "corbeli.ttf" },
        StaticSourceData { file_name: "corbell.ttf" },
        StaticSourceData { file_name: "corbelli.ttf" },
        StaticSourceData { file_name: "corbelz.ttf" },
        StaticSourceData { file_name: "cour.ttf" },
        StaticSourceData { file_name: "courbd.ttf" },
        StaticSourceData { file_name: "courbi.ttf" },
        StaticSourceData { file_name: "couri.ttf" },
        StaticSourceData { file_name: "ebrima.ttf" },
        StaticSourceData { file_name: "ebrimabd.ttf" },
        StaticSourceData { file_name: "framd.ttf" },
        StaticSourceData { file_name: "framdit.ttf" },
        StaticSourceData { file_name: "gabriola.ttf" },
        StaticSourceData { file_name: "gadugi.ttf" },
        StaticSourceData { file_name: "gadugib.ttf" },
        StaticSourceData { file_name: "georgia.ttf" },
        StaticSourceData { file_name: "georgiab.ttf" },
        StaticSourceData { file_name: "georgiai.ttf" },
        StaticSourceData { file_name: "georgiaz.ttf" },
        StaticSourceData { file_name: "himalaya.ttf" },
        StaticSourceData { file_name: "holomdl2.ttf" },
        StaticSourceData { file_name: "impact.ttf" },
        StaticSourceData { file_name: "inkfree.ttf" },
        StaticSourceData { file_name: "javatext.ttf" },
        StaticSourceData { file_name: "l_10646.ttf" },
        StaticSourceData { file_name: "leelauib.ttf" },
        StaticSourceData { file_name: "leelawui.ttf" },
        StaticSourceData { file_name: "leeluisl.ttf" },
        StaticSourceData { file_name: "lucon.ttf" },
        StaticSourceData { file_name: "msjhbd.ttc" },
        StaticSourceData { file_name: "malgun.ttf" },
        StaticSourceData { file_name: "malgunbd.ttf" },
        StaticSourceData { file_name: "malgunsl.ttf" },
        StaticSourceData { file_name: "marlett.ttf" },
        StaticSourceData { file_name: "micross.ttf" },
        StaticSourceData { file_name: "mingliub.ttc" },
        StaticSourceData { file_name: "mmrtext.ttf" },
        StaticSourceData { file_name: "mmrtextb.ttf" },
        StaticSourceData { file_name: "monbaiti.ttf" },
        StaticSourceData { file_name: "msgothic.ttc" },
        StaticSourceData { file_name: "msjh.ttc" },
        StaticSourceData { file_name: "msjhl.ttc" },
        StaticSourceData { file_name: "msyh.ttc" },
        StaticSourceData { file_name: "msyhbd.ttc" },
        StaticSourceData { file_name: "msyhl.ttc" },
        StaticSourceData { file_name: "msyi.ttf" },
        StaticSourceData { file_name: "mvboli.ttf" },
        StaticSourceData { file_name: "nirmala.ttf" },
        StaticSourceData { file_name: "nirmalab.ttf" },
        StaticSourceData { file_name: "nirmalas.ttf" },
        StaticSourceData { file_name: "ntailu.ttf" },
        StaticSourceData { file_name: "ntailub.ttf" },
        StaticSourceData { file_name: "pala.ttf" },
        StaticSourceData { file_name: "palab.ttf" },
        StaticSourceData { file_name: "palabi.ttf" },
        StaticSourceData { file_name: "palai.ttf" },
        StaticSourceData { file_name: "phagspab.ttf" },
        StaticSourceData { file_name: "phagspa.ttf" },
        StaticSourceData { file_name: "segmdl2.ttf" },
        StaticSourceData { file_name: "segoepr.ttf" },
        StaticSourceData { file_name: "segoeprb.ttf" },
        StaticSourceData { file_name: "segoesc.ttf" },
        StaticSourceData { file_name: "segoescb.ttf" },
        StaticSourceData { file_name: "segoeui.ttf" },
        StaticSourceData { file_name: "segoeuib.ttf" },
        StaticSourceData { file_name: "segoeuii.ttf" },
        StaticSourceData { file_name: "segoeuil.ttf" },
        StaticSourceData { file_name: "segoeuisl.ttf" },
        StaticSourceData { file_name: "segoeuiz.ttf" },
        StaticSourceData { file_name: "seguibl.ttf" },
        StaticSourceData { file_name: "seguibli.ttf" },
        StaticSourceData { file_name: "seguiemj.ttf" },
        StaticSourceData { file_name: "seguihis.ttf" },
        StaticSourceData { file_name: "seguili.ttf" },
        StaticSourceData { file_name: "seguisb.ttf" },
        StaticSourceData { file_name: "seguisbi.ttf" },
        StaticSourceData { file_name: "seguisli.ttf" },
        StaticSourceData { file_name: "seguisym.ttf" },
        StaticSourceData { file_name: "simsun.ttc" },
        StaticSourceData { file_name: "simsunb.ttf" },
        StaticSourceData { file_name: "sitka.ttc" },
        StaticSourceData { file_name: "sitkab.ttc" },
        StaticSourceData { file_name: "sitkai.ttc" },
        StaticSourceData { file_name: "sitkaz.ttc" },
        StaticSourceData { file_name: "sylfaen.ttf" },
        StaticSourceData { file_name: "symbol.ttf" },
        StaticSourceData { file_name: "tahoma.ttf" },
        StaticSourceData { file_name: "tahomabd.ttf" },
        StaticSourceData { file_name: "taileb.ttf" },
        StaticSourceData { file_name: "taile.ttf" },
        StaticSourceData { file_name: "times.ttf" },
        StaticSourceData { file_name: "timesbd.ttf" },
        StaticSourceData { file_name: "timesbi.ttf" },
        StaticSourceData { file_name: "timesi.ttf" },
        StaticSourceData { file_name: "trebuc.ttf" },
        StaticSourceData { file_name: "trebucbd.ttf" },
        StaticSourceData { file_name: "trebucbi.ttf" },
        StaticSourceData { file_name: "trebucit.ttf" },
        StaticSourceData { file_name: "verdana.ttf" },
        StaticSourceData { file_name: "verdanab.ttf" },
        StaticSourceData { file_name: "verdanai.ttf" },
        StaticSourceData { file_name: "verdanaz.ttf" },
        StaticSourceData { file_name: "webdings.ttf" },
        StaticSourceData { file_name: "wingding.ttf" },
        StaticSourceData { file_name: "yugothb.ttc" },
        StaticSourceData { file_name: "yugothl.ttc" },
        StaticSourceData { file_name: "yugothr.ttc" },
        StaticSourceData { file_name: "yugothm.ttc" },
    ],
    default_families: &[FontFamilyId(61)],
    script_fallbacks: &[
        StaticScriptFallbacks { script: *b"Adlm", families: &[FontFamilyId(15), ]},
        StaticScriptFallbacks { script: *b"Arab", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Armi", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Armn", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Beng", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Brah", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Brai", families: &[FontFamilyId(68), ]},
        StaticScriptFallbacks { script: *b"Bugi", families: &[FontFamilyId(24), ]},
        StaticScriptFallbacks { script: *b"Cakm", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Cans", families: &[FontFamilyId(18), ]},
        StaticScriptFallbacks { script: *b"Cari", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Cher", families: &[FontFamilyId(18), ]},
        StaticScriptFallbacks { script: *b"Cprt", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Cyrl", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Deva", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Egyp", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Ethi", families: &[FontFamilyId(15), ]},
        StaticScriptFallbacks { script: *b"Geok", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Geor", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Glag", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Goth", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Grek", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Gujr", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Guru", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Hang", families: &[FontFamilyId(28), ]},
        StaticScriptFallbacks { script: *b"Hebr", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Hira", families: &[FontFamilyId(85), ]},
        StaticScriptFallbacks { script: *b"Ital", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Java", families: &[FontFamilyId(23), ]},
        StaticScriptFallbacks { script: *b"Kana", families: &[FontFamilyId(85), ]},
        StaticScriptFallbacks { script: *b"Khar", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Khmr", families: &[FontFamilyId(24), ]},
        StaticScriptFallbacks { script: *b"Knda", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Laoo", families: &[FontFamilyId(24), ]},
        StaticScriptFallbacks { script: *b"Latn", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Lisu", families: &[FontFamilyId(61), ]},
        StaticScriptFallbacks { script: *b"Lyci", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Lydi", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Merc", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Mlym", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Mong", families: &[FontFamilyId(47), ]},
        StaticScriptFallbacks { script: *b"Mtei", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Mymr", families: &[FontFamilyId(52), ]},
        StaticScriptFallbacks { script: *b"Nkoo", families: &[FontFamilyId(15), ]},
        StaticScriptFallbacks { script: *b"Ogam", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Olck", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Orkh", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Orya", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Osma", families: &[FontFamilyId(15), ]},
        StaticScriptFallbacks { script: *b"Phag", families: &[FontFamilyId(37), ]},
        StaticScriptFallbacks { script: *b"Phli", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Phnx", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Prti", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Runr", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Sarb", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Shaw", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Sinh", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Sora", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Syrc", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Tale", families: &[FontFamilyId(39), ]},
        StaticScriptFallbacks { script: *b"Talu", families: &[FontFamilyId(36), ]},
        StaticScriptFallbacks { script: *b"Taml", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Telu", families: &[FontFamilyId(53), ]},
        StaticScriptFallbacks { script: *b"Tfng", families: &[FontFamilyId(15), ]},
        StaticScriptFallbacks { script: *b"Thaa", families: &[FontFamilyId(51), ]},
        StaticScriptFallbacks { script: *b"Thai", families: &[FontFamilyId(24), ]},
        StaticScriptFallbacks { script: *b"Tibt", families: &[FontFamilyId(31), ]},
        StaticScriptFallbacks { script: *b"Ugar", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Vaii", families: &[FontFamilyId(15), ]},
        StaticScriptFallbacks { script: *b"Xpeo", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Xsux", families: &[FontFamilyId(64), ]},
        StaticScriptFallbacks { script: *b"Yiii", families: &[FontFamilyId(44), ]},
        StaticScriptFallbacks { script: *b"Zsye", families: &[FontFamilyId(63), ]},
        StaticScriptFallbacks { script: *b"Zsym", families: &[FontFamilyId(63), FontFamilyId(68), ]},
    ],
    generic_families: [&[FontFamilyId(11), ], &[FontFamilyId(61), ], &[FontFamilyId(10), ], &[FontFamilyId(61), ], &[FontFamilyId(9), ], &[FontFamilyId(63), ], ],
    cjk_families: [&[FontFamilyId(40), FontFamilyId(69), FontFamilyId(70), ], &[FontFamilyId(40), FontFamilyId(69), FontFamilyId(70), ], &[FontFamilyId(32), FontFamilyId(45), ], &[FontFamilyId(85), FontFamilyId(40), FontFamilyId(69), FontFamilyId(70), ], &[FontFamilyId(28), FontFamilyId(40), FontFamilyId(69), FontFamilyId(70), ], ],
};





